version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "resume-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-v9s2anf4jiex"
s3_prefix = "resume-app"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
